In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data/2023_stats/2023_merged_data_final.csv')

In [3]:
df = df.dropna(subset=['Seed'])

In [4]:
df

,Team,Seed,DRebs,DRPG,SCR MAR,AST,TO,Ratio,PTS,PPG,...,OPP REB,OPP RPG,REB MAR,ORebs,ORPG,3FG%,3FG PG,REB,RPG,FT PG
0,A&M-CC (Southland),16.0,881,25.17,6.9,536.0,448.0,1.20,"2,803",80.1,...,"1,175",33.6,3.7,425.0,12.14,36.4,7.7,"1,306",37.31,16.9
4,Alabama (SEC),1.0,"1,168",31.57,13.5,555.0,512.0,1.08,"3,027",81.8,...,"1,383",37.4,7.3,484.0,13.08,33.5,9.9,"1,652",44.65,16.6
10,Arizona (Pac-12),2.0,"1,020",29.14,10.7,662.0,468.0,1.41,"2,866",81.9,...,"1,163",33.2,6.1,356.0,10.17,37.8,8.4,"1,376",39.31,15.0
11,Arizona St. (Pac-12),11.0,920,25.56,3.1,515.0,422.0,1.22,"2,559",71.1,...,"1,382",38.4,-1.9,395.0,10.97,32.2,7.6,"1,315",36.53,12.9
13,Arkansas (SEC),8.0,899,24.97,6.1,462.0,458.0,1.01,"2,666",74.1,...,"1,189",33.0,2.3,373.0,10.36,31.3,5.0,"1,272",35.33,15.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,VCU (Atlantic 10),12.0,837,23.91,7.9,456.0,468.0,0.97,"2,480",70.9,...,"1,157",33.1,0.1,324.0,9.26,34.8,6.1,"1,161",33.17,15.4
329,Vermont (America East),15.0,845,24.85,5.7,465.0,318.0,1.46,"2,471",72.7,...,"1,103",32.4,-1.1,220.0,6.47,35.8,8.6,"1,065",31.32,11.1
331,Virginia (ACC),4.0,791,23.97,7.3,519.0,282.0,1.84,"2,237",67.8,...,"1,055",32.0,0.3,273.0,8.27,35.0,6.7,"1,064",32.24,13.1
338,West Virginia (Big 12),9.0,769,22.62,5.1,442.0,440.0,1.00,"2,583",76.0,...,"1,062",31.2,2.6,383.0,11.26,35.0,7.3,"1,152",33.88,16.8
350,Xavier (Big East),3.0,"1,016",27.46,6.9,705.0,459.0,1.54,"2,995",80.9,...,"1,195",32.3,5.4,380.0,10.27,39.0,7.4,"1,396",37.73,13.6

In [5]:
kenpom_df = pd.read_csv('Data/2023_stats/2023_Kenpom.csv')

In [6]:
df['Team'] = df['Team'].str.replace(r"\s*\(.*\)", "", regex=True)

In [7]:
merged_df = df.merge(kenpom_df, on='Team', how='inner')  # Change 'how' as needed

In [8]:
merged_df

,Team,Seed,DRebs,DRPG,SCR MAR,AST,TO,Ratio,PTS,PPG,...,NetRtg,ORtg,DRtg,AdjT,Luck,Opp NetRtg,Opp ORtg,Opp DRtg,Non Conf Opp NetRtg,Unnamed: 11
0,Alabama,1.0,"1,168",31.57,13.5,555.0,512.0,1.08,"3,027",81.8,...,27.28,115.5,88.2,72.6,0.057,11.07,110.2,99.2,10.46,NaN
1,Arizona,2.0,"1,020",29.14,10.7,662.0,468.0,1.41,"2,866",81.9,...,21.90,118.2,96.3,72.0,0.027,8.32,107.5,99.2,3.12,NaN
2,Arizona St.,11.0,920,25.56,3.1,515.0,422.0,1.22,"2,559",71.1,...,13.26,109.0,95.8,68.1,0.047,8.40,108.4,100.0,0.78,NaN
3,Arkansas,8.0,899,24.97,6.1,462.0,458.0,1.01,"2,666",74.1,...,18.05,112.1,94.0,69.6,-0.042,10.29,109.7,99.4,3.24,NaN
4,Auburn,9.0,835,24.56,5.1,479.0,414.0,1.16,"2,474",72.8,...,16.77,112.5,95.7,67.6,-0.018,9.68,109.4,99.7,3.38,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,VCU,12.0,837,23.91,7.9,456.0,468.0,0.97,"2,480",70.9,...,12.84,106.6,93.8,67.9,0.020,0.79,105.0,104.2,-1.77,NaN
59,Vermont,15.0,845,24.85,5.7,465.0,318.0,1.46,"2,471",72.7,...,5.33,109.5,104.2,64.4,0.049,-3.01,103.5,106.5,5.54,NaN
60,Virginia,4.0,791,23.97,7.3,519.0,282.0,1.84,"2,237",67.8,...,16.37,110.8,94.5,61.5,0.027,5.73,108.4,102.7,1.52,NaN
61,West Virginia,9.0,769,22.62,5.1,442.0,440.0,1.00,"2,583",76.0,...,18.82,116.9,98.1,68.5,-0.068,12.45,110.5,98.1,2.18,NaN
62,Xavier,3.0,"1,016",27.46,6.9,705.0,459.0,1.54,"2,995",80.9,...,19.95,118.5,98.6,70.5,0.005,10.42,110.3,99.9,3.40,NaN

In [9]:
merged_df.to_csv('Data/2023_stats/2023_data.csv', index=False)